### ISSUE TITLE
Design Homepage for the website.

### ISSUE THREAD

**Issue by TheInspiredConjurer** [TheInspiredConjurer/Online-Questionnaire-System#1]
Design a Homepage for the website.

It should have a navbar with the following links: HOME, PRACTICE, LOGIN, REGISTER.

The main content should be designed keeping in mind the requirements of the website. Even better if its original content.
 
Feel free to style it as you wish.

**Note:**
----------
1. **Design must be original. DO NOT COPY DESIGNS FROM OTHER WEBSITES!!!** You are free to use other websites as a reference, but the design should be your original design.
1. **Site must be RESPONSIVE**
2. **If using code, it must be made using Tailwind CSS v3.1.8 or newer**

Good to have (but not required): 
----------------------------------
The page must be its own Vue Component titled `HomePage.vue`

**Comment by alkhimch** [comment]
please assign to me this task. I am vue, django developer

**Comment by TheInspiredConjurer** [comment]
@alkhimch Sure, go ahead!

**Comment by TheInspiredConjurer** [comment]
@alkhimch Are you done? If not, I will assign someone else.

**Comment by alkhimch** [comment]
@TheInspiredConjurer I am working on this :)

**Comment by TheInspiredConjurer** [comment]
cool, then

**Comment by TheInspiredConjurer** [comment]
Hey @alkhimch it has been more than a week since you were assigned this task. Are you still working on it or should I assign this to someone else?

**Comment by justDabuK** [comment]
In case @alkhimch is not interested anymore, I'd love to do this 🙋🏽‍♂️

**Comment by alkhimch** [comment]
@justDabuK you can do this.

**Comment by TheInspiredConjurer** [comment]
@justDabuK go ahead!

**Comment by justDabuK** [comment]
Noice I'll latest start on Monday 👍🏽

**Comment by justDabuK** [comment]
Hey @TheInspiredConjurer , 

What is it actually you'd like to have as content on the home page? 🤔 

I can (and will) prepare the basic look and the navigation, but I'll probably need some input for the home page content itself? 🤔

**Comment by TheInspiredConjurer** [comment]
> Hey @TheInspiredConjurer ,
> 
> What is it actually you'd like to have as content on the home page? 🤔
> 
> I can (and will) prepare the basic look and the navigation, but I'll probably need some input for the home page content itself? 🤔

A navbar for login, regsiter, questions, solutions. Something about the website and the features it offers. How it works, Testimonials by students, For now... this much.

You can take some reference from other similar websites.

Here are some from my side:
https://www.embibe.com/

**Comment by justDabuK** [comment]
I guess I can add similar info to the one we have in the Readme currently, but currently we can neither add how it works nor testimonials, since it neither works yet, nor do any testimonials exist right? 🤔 

Would it be ok then, if I go with the navbar and what the planned features are for now? 
Once we have more info to display, we can always extend the home page 🤔

**Comment by TheInspiredConjurer** [comment]
> I guess I can add similar info to the one we have in the Readme currently, but currently we can neither add how it works nor testimonials, since it neither works yet, nor do any testimonials exist right? 🤔
> 
> Would it be ok then, if I go with the navbar and what the planned features are for now? Once we have more info to display, we can always extend the home page 🤔

Yeah, sounds good for now. Go ahead 👍

**Comment by justDabuK** [comment]
My PR (https://github.com/TheInspiredConjurer/Online-Questionnaire-System/pull/20) is review ready ☝🏽 

I am now designer, which is why it still looks quite rudimentary, but I think it's a good start for a home page 🤷🏽‍♂️ 

Plus I setup tailwind and added the navigation bar, which I think is both quite necessary for the next issues 😌
