### ISSUE TITLE
Replace names of technologies in 'Tech Stack Used' in READMe.md with their respective icons.

### ISSUE THREAD

**Issue by TheInspiredConjurer** [TheInspiredConjurer/Online-Questionnaire-System#12]
So, Currently the content used in 'Tech Stack Used' in the README.md section is pure text
like "HTML5, CSS3,", etc.

Replace them with their respective icons.

You can find the icons in the `readme icons` folder in the repository.

All you have to do is find some way to show that image in the README.md file.

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.

**Comment by TheInspiredConjurer** [comment]
Sure! Go ahead! @Anish-Sarawgi

**Comment by ShishuSidharth** [comment]
Can you please  assign this to me  for hacktoberfest

**Comment by TheInspiredConjurer** [comment]
@ShishuSidharth Hey! Sorry, but this issue has been assigned to someone else! Why dont you try working on #3 ?

**Comment by TheInspiredConjurer** [comment]
Looks Good! Thanks a lot!
