### ISSUE TITLE
Error creating superuser

### ISSUE THREAD

**Issue by LunlunChin** [TheInspiredConjurer/Online-Questionnaire-System#18]
I was trying to create a superuser to access the admin dashboard, but I got the error below

`django.db.utils.OperationalError: no such table: accounts_user
`

may I know how do I solve this issue? 
Thanks!

**Comment by Vir2S** [comment]
you need to do migrations. python3 manage.py makemigrations and python3 manage.py migrate - that's all

**Comment by TheInspiredConjurer** [comment]
@LunlunChin ther you go. Hope you got your answer from Vitaly :)
