### ISSUE TITLE
Design About Us Page for the website

### ISSUE THREAD

**Issue by TheInspiredConjurer** [TheInspiredConjurer/Online-Questionnaire-System#2]
Design an 'About Us' page for the website.

It should have a navbar with the following links: HOME, PRACTICE, LOGIN, REGISTER.

The main content should contain details of the project such as Tech Stack used, Contact Us links, etc.
 
Feel free to style it as you wish.

**Note:**
----------
1. **Design must be original. DO NOT COPY DESIGNS FROM OTHER WEBSITES!!!** You are free to use other websites as a reference, but the design should be your original design.
1. **Site must be RESPONSIVE**
2. **If using code, it must be made using Tailwind CSS v3.1.8 or newer**

Good to have (but not required): 
----------------------------------
The page must be its own Vue Component titled `AboutUsPage.vue`

**Comment by alkhimch** [comment]
please assign to me this task. I am vue, django developer

**Comment by TheInspiredConjurer** [comment]
@alkhimch You have already been assigned an issue. Kindly complete that first. Good Luck!

**Comment by snowrlax** [comment]
Hey, can you please assign this issue to me?
Also is Tailwind CSS mandatory?

**Comment by TheInspiredConjurer** [comment]
@snowrlax As mentioned in the requirements, if you are going to submit code, then only use Tailwind CSS...

However, if you are going to submit a design instead of code, then feel free to do it using whatever tools you want. However, the design must be original.

**Comment by snowrlax** [comment]
okay will do👍

**Comment by TheInspiredConjurer** [comment]
Hey @snowrlax are you still working on this issue? or should I assign this to someone else?

**Comment by justDabuK** [comment]
In case @snowrlax is not interested anymore, I'd also love to do this 🙋🏽‍♂️

**Comment by TheInspiredConjurer** [comment]
@snowrlax Since you haven't replied to this issue, I'm assigning this to Dabuk. Let me know when you're done.

**Comment by justDabuK** [comment]
Oh you don't want to have it anymore? 🤔
