### ISSUE TITLE
Add ESLint and prettier 

### ISSUE THREAD

**Issue by justDabuK** [TheInspiredConjurer/Online-Questionnaire-System#21]
Hello, 

I think it would be helpful for all frontend developers to use [ESLint](https://eslint.org/) in combination with [prettier](https://prettier.io/). This would allow developers to activate "lint on save" in their IDEs. This will automagically reformat their code and will ensure a consistent style throughout the application.

**Comment by justDabuK** [comment]
Hey @TheInspiredConjurer , 

during building the Homepage, I really missed having eslint and prettier, which auto reformat my code whenever I hit the save button. Additionally it will also help future contributors to have adapt the codestyle and to not do any common mistakes. Having these in frontend projects is a must have in my opinion. 

Would it be ok to you if I first work on this one, before I start with the AboutPage? 🤔

**Comment by TheInspiredConjurer** [comment]
Sure, I don't mind, but please use Options API of Vue 3, not Composition.

I don't know Composition

**Comment by justDabuK** [comment]
Oh sorry I didn't know that, then I'll change the components we have so far 👍🏽

**Comment by justDabuK** [comment]
I created https://github.com/TheInspiredConjurer/Online-Questionnaire-System/pull/22 in order to add eslint and prettier, solve all eslint error and to refactor the components to use the options API 👌🏽
