### ISSUE TITLE
Authentication and Authorization with JWT

### ISSUE THREAD

**Issue by TheInspiredConjurer** [TheInspiredConjurer/Online-Questionnaire-System#9]
- Implement Authentication and Authorization in the entire application according to the models `user` and `role` in the database schema image mentioned in #3 

- Authentication is to be required for accessing the whole site, except the home page and about us... In other words, except the Home page and About Us Page, every other page needs to be accessed by an authenticated user.

- Implement role-based authorization. For example, a `student` can neither edit nor delete any questions or choices. They can only view and select them. Similarly, a `teacher` should only be able to view a student profile. They can neither edit nor delete them.

- Implement JWT authentication by using REST Framework's [SimpleJWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/)

**Comment by Vir2S** [comment]
I'll do it!

**Comment by TheInspiredConjurer** [comment]
Sure! go ahead!
